name: Deploy
on: [push, pull_request]
jobs:
  deploy:
    name: build dependencies & create artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Build JS dependencies
        uses: PrestaShopCorp/github-action-build-js/12@dev
        with:
          cmd: yarn
          path: ./_dev
      - name: Install composer dependencies
        run: composer install --no-dev -o
      - name: Clean-up project
        uses: PrestaShopCorp/github-action-clean-before-deploy@dev
        with:
          path: "docs upgrade"
      - name: Create & upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: ps_checkout
          path: ../
